//! Fonts bundled from `data/fonts`, for the no-art panel to draw with.
//!
//! The table is generated by `build.rs`, which reads each family name out of the
//! font's own `name` table - dropping a file into that directory is the whole
//! procedure, with no list to maintain here. An empty directory is normal: the
//! panel then uses the default sans family.
//!
//! **Pango cannot be handed a font from memory.** It finds fonts through
//! fontconfig, which only looks in the directories it is configured with, and
//! neither exposes an "add these bytes" call through the bindings this project
//! has. So the bundled files are written into `$XDG_DATA_HOME/fonts/trayplay/` -
//! a standard user font directory - before GTK initialises, and fontconfig picks
//! them up from there when it builds its config.
//!
//! The cost, documented rather than hidden: those fonts become visible to every
//! other application on the machine, exactly as if they had been installed by
//! hand. There is no way around that short of adding a fontconfig C binding, and
//! this machine has no crates.io access to add one with.

use std::path::PathBuf;
use std::sync::OnceLock;

use anyhow::{Context, Result};

pub struct Font {
    /// File name, which is also what it is written out as.
    pub file: &'static str,
    /// Family name, as Pango will resolve it.
    pub family: &'static str,
    pub bytes: &'static [u8],
}

include!(concat!(env!("OUT_DIR"), "/fonts.rs"));

/// Families successfully installed, in the order `build.rs` listed them.
static AVAILABLE: OnceLock<Vec<&'static str>> = OnceLock::new();

/// Writes the bundled fonts out and records which families can be used.
///
/// Must run **before GTK is initialised**: fontconfig reads its directories when
/// it builds its configuration, and a font written after that is not seen until
/// the next launch. Failures are per-font and non-fatal - a family that could not
/// be written is left out of the list rather than stopping startup over
/// decoration.
pub fn install() -> Result<()> {
    if FONTS.is_empty() {
        AVAILABLE.get_or_init(Vec::new);
        return Ok(());
    }

    let dir = font_dir()?;
    std::fs::create_dir_all(&dir)
        .with_context(|| format!("creating {}", dir.display()))?;

    let mut available = Vec::new();
    for font in FONTS {
        let path = dir.join(font.file);
        // Size is enough of a check: these files change only when one is
        // replaced in the source tree, and rewriting them on every launch would
        // touch the directory and make fontconfig rescan for nothing.
        let current = std::fs::metadata(&path).map(|meta| meta.len()).ok();
        if current != Some(font.bytes.len() as u64) {
            match std::fs::write(&path, font.bytes) {
                Ok(()) => tracing::info!(font = font.file, "installed bundled font"),
                Err(err) => {
                    tracing::warn!(%err, font = font.file, "cannot install bundled font");
                    continue;
                }
            }
        }
        available.push(font.family);
    }

    tracing::debug!(count = available.len(), dir = %dir.display(), "bundled fonts ready");
    AVAILABLE.get_or_init(|| available);
    Ok(())
}

/// The families available to draw with. Empty until `install` has run, and
/// empty for good if `data/fonts` holds nothing.
pub fn families() -> &'static [&'static str] {
    AVAILABLE.get().map(Vec::as_slice).unwrap_or(&[])
}

/// Where the fonts are written. `$XDG_DATA_HOME/fonts` is one of fontconfig's
/// default directories, so no fontconfig configuration has to be written; the
/// subdirectory keeps trayplay's own files identifiable.
fn font_dir() -> Result<PathBuf> {
    let dirs = directories::BaseDirs::new().context("cannot determine XDG base directories")?;
    Ok(dirs.data_dir().join("fonts").join("trayplay"))
}
